apiVersion: v1
kind: Namespace
metadata:
  name: expert-llm-system
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: expert-llm-serviceaccount
  namespace: expert-llm-system
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: expert-llm-reader
rules:
- apiGroups: [""]
  resources: ["pods", "services", "nodes"]
  verbs: ["get", "list", "watch"]
- apiGroups: ["apps"]
  resources: ["deployments", "replicasets"]
  verbs: ["get", "list", "watch"]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: expert-llm-binding
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: expert-llm-reader
subjects:
- kind: ServiceAccount
  name: expert-llm-serviceaccount
  namespace: expert-llm-system
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: expert-llm-config
  namespace: expert-llm-system
data:
  LOG_LEVEL: "INFO"
  STREAMLIT_SERVER_PORT: "8501"
  STREAMLIT_SERVER_ADDRESS: "0.0.0.0"
  STREAMLIT_SERVER_HEADLESS: "true"
  STREAMLIT_BROWSER_GATHER_USAGE_STATS: "false"
  SAFETY_MODE: "enabled"
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: expert-llm-system
  namespace: expert-llm-system
  labels:
    app: expert-llm-system
spec:
  replicas: 1
  selector:
    matchLabels:
      app: expert-llm-system
  template:
    metadata:
      labels:
        app: expert-llm-system
    spec:
      serviceAccountName: expert-llm-serviceaccount
      containers:
      - name: expert-llm-system
        image: localhost/expert-llm-system:latest
        imagePullPolicy: Never  # Use local image
        ports:
        - containerPort: 8501
          name: http
        envFrom:
        - configMapRef:
            name: expert-llm-config
        resources:
          requests:
            memory: "1Gi"
            cpu: "500m"
          limits:
            memory: "2Gi"
            cpu: "1000m"
---
apiVersion: v1
kind: Service
metadata:
  name: expert-llm-service
  namespace: expert-llm-system
  labels:
    app: expert-llm-system
spec:
  type: NodePort
  ports:
  - port: 8501
    targetPort: 8501
    nodePort: 30501
    protocol: TCP
    name: streamlit
  - port: 11434
    targetPort: 11434
    nodePort: 30434
    protocol: TCP
    name: ollama
  selector:
    app: expert-llm-system
